---
- name: Redis Node Management
  hosts: 'all:!localhost'
  gather_facts: true
  become: true
  vars:
    subscription_manager_rhsm_username: '{{ rhsm_username }}'
    subscription_manager_rhsm_password: '{{ rhsm_password }}'
    subscription_manager_no_log_setting: '{{ no_log_setting | default(true) }}'
  tasks:
    - name: Register RHEL and Manage Redis
      ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - subscription_manager
        - manage_redis
